### ISSUE TITLE
Pop up warning about deleting all reviews only displayed when ADD question, not REMOVE

### ISSUE THREAD

**Issue by BoergerJ** [BoergerJ/expertiza#14]
A pop-up warning about deleting all reviews appears when adding a question. This does not appear when deleting a question

**Comment by BoergerJ** [comment]
This is referenced in the comments on the previous team:
"If you are in the active period, you get a message that if you remove a question, there should be a confirmation prompt/alert prompted to the instructor.(This is because the remove happens from a completely diff. place in the code where it is not so convenient.)"

add_new_questions() method is called in app/views/questionnaires/_questionnaire.html.erb
By pushing the "Add" button it calls the in_active_period() method and throws the pop-up

Deleting of questions occurs in each of the question types models as they call data-method="delete" through the HTML for the table which creates the "Remove" button. Making it very difficult to render a pop-up based on this action.

To resolve this, do we want to render the pop-up when the instructor tries to save the edits instead?

**Comment by BoergerJ** [comment]
Cannot use save button to implement this change.

Save button saves content of questions, not changes to the structure of the questionnaire. Add and remove are saved as soon as they happen.

**Comment by nnhimes** [comment]
It still does not work for me, I only get a popup when adding a new question. Can't the active period check be done the same way for delete question as it is for adding a new one?
